#!/usr/bin/env bash
# This script displays the content of the current directory, showing only the part after the first dash
for file in *
do
    if [[ "$file" != .* ]]
    then
        echo "$file" | cut -d'-' -f2-
    fi
done
